### ISSUE TITLE
does not compile with current version of yosys v0.50

### ISSUE THREAD

**Issue by gadfort** [Coloquinte/moosic-yosys-plugin#30]
When compiling with yosys v0.50 I get the following:
```
rc/logic_locking_analyzer.cpp: In member function ‘Yosys::RTLIL::Const LogicLockingAnalyzer::get_state(Yosys::RTLIL::SigSpec)’:
src/logic_locking_analyzer.cpp:517:31: error: invalid use of member function ‘std::vector<Yosys::RTLIL::State>& Yosys::RTLIL::Const::bits()’ (did you forget the ‘()’ ?)
  517 |                         value.bits.push_back(bit.data);
      |                         ~~~~~~^~~~
      |                                   ()
src/logic_locking_analyzer.cpp:519:31: error: invalid use of member function ‘std::vector<Yosys::RTLIL::State>& Yosys::RTLIL::Const::bits()’ (did you forget the ‘()’ ?)
  519 |                         value.bits.push_back(state_.at(bit));
      |                         ~~~~~~^~~~
      |                                   ()
src/logic_locking_analyzer.cpp:521:31: error: invalid use of member function ‘std::vector<Yosys::RTLIL::State>& Yosys::RTLIL::Const::bits()’ (did you forget the ‘()’ ?)
  521 |                         value.bits.push_back(State::Sz);
      |                         ~~~~~~^~~~
      |                                   ()
make: *** [Makefile:49: logic_locking_analyzer.o] Error 1
```

**Comment by Coloquinte** [comment]
Fixed this in the latest release
